# Generated by Django 6.0.3 on 2026-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
                ('base_fare', models.IntegerField(default=5000, verbose_name="Boshlang'ich narx (UZS)")),
                ('per_km_rate', models.IntegerField(default=2000, verbose_name='Har km narxi (UZS)')),
                ('shared_discount', models.FloatField(default=0.3, verbose_name='Sherikli chegirma (%)')),
                ('commission_rate', models.FloatField(default=0.05, verbose_name='Komissiya stavkasi (%)')),
                ('min_fare', models.IntegerField(default=3000, verbose_name='Minimal narx (UZS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Narx qoidasi',
                'verbose_name_plural': 'Narx qoidalari',
            },
        ),
    ]
