# Generated by Django 6.0.3 on 2026-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='cancellation_fee',
            field=models.IntegerField(default=2000, verbose_name='Bekor qilish jarimasi (UZS)'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='waiting_rate_per_min',
            field=models.IntegerField(default=500, verbose_name='Kutish narxi (minutiga, UZS)'),
        ),
    ]
