# Generated by Django 6.0.3 on 2026-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricingrule_cancellation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='multi_stop_fee',
            field=models.IntegerField(default=2000, verbose_name="Qo'shimcha to'xtash narxi (UZS)"),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='scheduled_fee',
            field=models.IntegerField(default=5000, verbose_name='Oldindan band qilish narxi (UZS)'),
        ),
    ]
