# Generated by Django 5.1.4 on 2026-07-07 08:53

import pricing.models
from django.db import migrations, models


def backfill_existing_rules(apps, schema_editor):
    """Mavjud narx qoidalariga standart klass tariflarini va 20% komissiyani qo'yamiz."""
    PricingRule = apps.get_model('pricing', 'PricingRule')
    defaults = pricing.models.default_tariff_categories()
    for rule in PricingRule.objects.all():
        changed = False
        if not rule.categories:
            rule.categories = defaults
            changed = True
        # Eski standart 5% komissiyani 20% ga yangilaymiz (admin keyin o'zgartira oladi)
        if rule.commission_rate in (0.05, 0.5, None):
            rule.commission_rate = 0.20
            changed = True
        if changed:
            rule.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricingrule_multi_stop_fee_pricingrule_scheduled_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='categories',
            field=models.JSONField(blank=True, default=pricing.models.default_tariff_categories, verbose_name='Klass tariflari'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='commission_rate',
            field=models.FloatField(default=0.2, verbose_name='Komissiya stavkasi (%)'),
        ),
        migrations.RunPython(backfill_existing_rules, noop),
    ]
