# Generated by Django 5.1.4 on 2026-04-02 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('icon', models.CharField(choices=[('home', 'Uy'), ('briefcase', 'Ish'), ('star', 'Sevimli'), ('school', 'Maktab'), ('location', 'Boshqa')], default='location', max_length=20, verbose_name='Ikonka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Saqlangan manzil',
                'verbose_name_plural': 'Saqlangan manzillar',
                'ordering': ['-created_at'],
            },
        ),
    ]
