# Generated by Django 6.0.3 on 2026-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='penalty_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jarima balansi (UZS)'),
        ),
    ]
