# Generated by Django 6.0.3 on 2026-04-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_penalty_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon name for mobile app', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nishon',
                'verbose_name_plural': 'Nishonlar',
            },
        ),
        migrations.CreateModel(
            name='DriverGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('goal_type', models.CharField(choices=[('daily', 'Kunlik'), ('monthly', 'Oylik')], max_length=10)),
                ('target_rides', models.IntegerField()),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maqsad',
                'verbose_name_plural': 'Maqsadlar',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='gold_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GoldPoints'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referal kod'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilgan foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='DriverBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.driver')),
            ],
            options={
                'verbose_name': 'Haydovchi nishoni',
                'verbose_name_plural': 'Haydovchi nishonlari',
                'unique_together': {('driver', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sevimli haydovchi',
                'verbose_name_plural': 'Sevimli haydovchilar',
                'unique_together': {('user', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to='accounts.driver')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.drivergoal')),
            ],
            options={
                'verbose_name': 'Maqsad taraqqiyoti',
                'verbose_name_plural': 'Maqsadlar taraqqiyoti',
                'unique_together': {('driver', 'goal', 'date')},
            },
        ),
    ]
