# Generated by Django 6.0.3 on 2026-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_badge_drivergoal_user_gold_points_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Ekonom'), ('comfort', 'Komfort'), ('business', 'Biznes')], default='economy', max_length=10, verbose_name='Sinf (Ekonom/Komfort/Biznes)'),
        ),
    ]
