# Generated by Django 6.0.3 on 2026-04-21 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vehicle_car_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Bank hisob raqami'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balans (Oltin tanga)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hamyon',
                'verbose_name_plural': 'Hamyonlar',
            },
        ),
    ]
