# Generated by Django 6.0.3 on 2026-04-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_bank_account_id_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('topup', "To'ldirish"), ('payment', "To'lov"), ('withdraw', 'Yechish'), ('refund', 'Qaytarish'), ('bonus', 'Bonus')], max_length=10, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Xato')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet', verbose_name='Hamyon')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
