# Generated by Django 6.0.3 on 2026-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID raqami'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kutilayotgan referal bonus (UZS)'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_rides_count',
            field=models.IntegerField(default=0, verbose_name="Do'stining safarlari soni (Referal uchun)"),
        ),
    ]
