# Generated by Django 6.0.3 on 2026-04-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_id_number_user_pending_referral_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancellation_count',
            field=models.IntegerField(default=0, verbose_name='Ketma-ket bekor qilishlar soni'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_cancellation_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi bekor qilish vaqti'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Ekonom (Start)'), ('comfort', 'Komfort'), ('business', 'Biznes'), ('electro', 'Elektro')], default='economy', max_length=10, verbose_name='Sinf (Ekonom/Komfort/Biznes)'),
        ),
    ]
