# Generated by Django 6.0.3 on 2026-05-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cancellation_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus balansi (UZS)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
    ]
