# Generated by Django 6.0.3 on 2026-05-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_bonus_balance_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_class',
            field=models.CharField(choices=[('start', 'Start'), ('comfort', 'Komfort'), ('business', 'Biznes'), ('electro', 'Elektro')], default='economy', max_length=10, verbose_name='Sinf (Ekonom/Komfort/Biznes)'),
        ),
    ]
