# Generated by Django 6.0.3 on 2026-05-11 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_device_id_user_last_ip_alter_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Ekonom'), ('comfort', 'Komfort'), ('business', 'Biznes'), ('electro', 'Elektro')], default='economy', max_length=10, verbose_name='Sinf (Ekonom/Komfort/Biznes)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Marka kamida 2 ta harf yoki raqamdan iborat bo'lishi kerak", regex='^[a-zA-Z0-9\\s\\-а-яА-ЯёЁ]{2,50}$')], verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Model kamida 2 ta harf yoki raqamdan iborat bo'lishi kerak", regex='^[a-zA-Z0-9\\s\\-а-яА-ЯёЁ]{2,50}$')], verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Davlat raqami noto'g'ri formatda (Masalan: 01A123AA yoki 01123AAA).", regex='^(?:\\d{2}[A-Z]\\d{3}[A-Z]{2}|\\d{2}\\d{3}[A-Z]{3})$')], verbose_name='Davlat raqami'),
        ),
        migrations.CreateModel(
            name='WalletRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('deposit', "To'ldirish"), ('withdraw', 'Yechish')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Hamyon so'rovi",
                'verbose_name_plural': "Hamyon so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
