# Generated by Django 6.0.3 on 2026-05-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_telegram_username_alter_vehicle_car_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
    ]
