# Generated by Django 6.0.3 on 2026-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passenger_rating',
            field=models.FloatField(default=5.0, verbose_name="Yo'lovchi reytingi"),
        ),
        migrations.AddField(
            model_name='user',
            name='total_passenger_rides',
            field=models.IntegerField(default=0, verbose_name="Jami yo'lovchi safarlari"),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
    ]
