# Generated by Django 6.0.3 on 2026-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_passenger_rating_user_total_passenger_rides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='face_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='face_id/', verbose_name='Face ID rasmi'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/', verbose_name='Guvohnoma rasmi (Orqa)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='passport_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='passports/', verbose_name='Pasport rasmi (Orqa)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='passport_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='passports/', verbose_name='Pasport rasmi (Oldi)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='taxi_license_photo',
            field=models.FileField(blank=True, null=True, upload_to='taxi_licenses/', verbose_name='Taksi litsenziyasi (PDF/Rasm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='Shartnomaga rozilik'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/interior/', verbose_name='Salon rasmi 1'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/interior/', verbose_name='Salon rasmi 2'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Mashina rasmi (Orqa)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_left',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Mashina rasmi (Chap)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_right',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name="Mashina rasmi (O'ng)"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tech_passport_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='tech_passports/', verbose_name='Texpasport rasmi (Orqa)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tech_passport_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='tech_passports/', verbose_name='Texpasport rasmi (Oldi)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/', verbose_name='Guvohnoma rasmi (Oldi)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Mashina rasmi (Oldi)'),
        ),
    ]
