# Generated by Django 5.1.4 on 2026-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_driver_face_id_photo_driver_license_photo_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_being_requested',
            field=models.BooleanField(default=False, help_text="True bo'lsa, haydovchi hozir yangi so'rov kutmoqda — boshqa so'rov yuborilmaydi.", verbose_name="So'rov kutilmoqda"),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_requests_received',
            field=models.IntegerField(default=0, verbose_name="Qabul qilingan so'rovlar"),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_rides_completed',
            field=models.IntegerField(default=0, verbose_name='Tugatilgan safarlar'),
        ),
    ]
