# Generated by Django 5.1.4 on 2026-06-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_driver_lock_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=13, verbose_name='Telefon raqami')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP kodi')),
                ('chat_id', models.CharField(blank=True, max_length=20, verbose_name='Telegram Chat ID')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram OTP',
                'verbose_name_plural': 'Telegram OTPlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='drivergoal',
            options={'ordering': ['min_rides'], 'verbose_name': 'Haydovchi maqsadi', 'verbose_name_plural': 'Haydovchi maqsadlari'},
        ),
        migrations.AlterUniqueTogether(
            name='goalprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='drivergoal',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='drivergoal',
            name='reward_amount',
        ),
        migrations.RemoveField(
            model_name='drivergoal',
            name='target_rides',
        ),
        migrations.AddField(
            model_name='driver',
            name='commission_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Komissiya chegirmasi (%)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='commission_discount_until',
            field=models.DateField(blank=True, null=True, verbose_name='Komissiya chegirmasi (gacha)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='intro_period_completed',
            field=models.BooleanField(default=False, help_text="True bo'lsa, oddiy komissiya qo'llanadi", verbose_name='Kirish davri tugagan'),
        ),
        migrations.AddField(
            model_name='driver',
            name='intro_period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kirish davri boshlangan vaqt'),
        ),
        migrations.AddField(
            model_name='driver',
            name='referred_by_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_drivers', to='accounts.driver', verbose_name='Taklif qilgan haydovchi'),
        ),
        migrations.AddField(
            model_name='drivergoal',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pul mukofoti (UZS)'),
        ),
        migrations.AddField(
            model_name='drivergoal',
            name='commission_discount_days',
            field=models.IntegerField(default=3, verbose_name='Komissiya chegirmasi davomiyligi (kun)'),
        ),
        migrations.AddField(
            model_name='drivergoal',
            name='commission_discount_percent',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Komissiya chegirmasi (%)'),
        ),
        migrations.AddField(
            model_name='drivergoal',
            name='extra_orders_bonus',
            field=models.IntegerField(default=10, verbose_name="Qo'shimcha buyurtmalar bonusi"),
        ),
        migrations.AddField(
            model_name='drivergoal',
            name='min_rides',
            field=models.IntegerField(default=0, verbose_name='Kerakli buyurtmalar soni'),
        ),
        migrations.AddField(
            model_name='drivergoal',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='drivergoal',
            name='period_days',
            field=models.IntegerField(default=3, verbose_name='Maqsad davri (kun)'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='reward_paid',
            field=models.BooleanField(default=False, verbose_name='Mukofot berildi'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlash sanasi'),
        ),
        migrations.AddField(
            model_name='goalprogress',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('completed', 'Bajarildi'), ('failed', 'Bajarilmadi')], default='active', max_length=10, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='drivergoal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='drivergoal',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Nomi'),
        ),
        migrations.RemoveField(
            model_name='goalprogress',
            name='date',
        ),
        migrations.RemoveField(
            model_name='goalprogress',
            name='is_completed',
        ),
    ]
