# Generated by Django 5.1.4 on 2026-06-04 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_seed_driver_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Park nomi')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='Telefon')),
                ('contact_person', models.CharField(max_length=100, verbose_name="Mas'ul shaxs")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='INN')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('blocked', 'Bloklangan')], default='pending', max_length=10, verbose_name='Status')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='taxi_parks/', verbose_name='Logo')),
                ('api_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='API token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taksi parki',
                'verbose_name_plural': 'Taksi parklari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='taxi_park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='accounts.taxipark', verbose_name='Taksi parki'),
        ),
    ]
