# Generated by Django 5.1.4 on 2026-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_taxi_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxipark',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Parol'),
        ),
    ]
