# Generated by Django 5.1.4 on 2026-06-12 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_taxipark_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Referal balansi (yechib olinadigan, UZS)'),
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor (UZS)')),
                ('source', models.CharField(choices=[('passenger', "Yo'lovchi do'st safari"), ('driver', 'Haydovchi referal')], default='passenger', max_length=12)),
                ('payment_method', models.CharField(blank=True, max_length=10, verbose_name="To'lov usuli")),
                ('is_credited', models.BooleanField(default=False, verbose_name="Balansga o'tkazilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_earnings_generated', to=settings.AUTH_USER_MODEL, verbose_name='Kimdan (taklif qilingan)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to=settings.AUTH_USER_MODEL, verbose_name='Bonus oluvchi (taklif qilgan)')),
            ],
            options={
                'verbose_name': 'Referal daromad',
                'verbose_name_plural': 'Referal daromadlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
