# Generated by Django 6.0.6 on 2026-07-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_set_goal_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="Ro'yxatdan o'tgan IP"),
        ),
    ]
