# Generated by Django 5.1.4 on 2026-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_registration_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxipark',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text="Park egasi yangi haydovchi so'rovlari haqida shu chatga xabar oladi.", max_length=32, verbose_name='Telegram chat ID'),
        ),
    ]
