# Generated by Django 5.1.4 on 2026-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_backfill_referral_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bloklash sababi'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloklangan vaqti'),
        ),
    ]
