# Generated by Django 6.0.3 on 2026-03-31 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('searching', 'Qidirilmoqda'), ('driver_found', 'Haydovchi topildi'), ('on_the_way', "Yo'lda"), ('started', 'Boshlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='searching', max_length=15, verbose_name='Status')),
                ('is_shared', models.BooleanField(default=True, verbose_name='Sherikli safar')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami narx (UZS)')),
                ('total_distance', models.FloatField(default=0, verbose_name='Jami masofa (km)')),
                ('commission_rate', models.FloatField(default=0.05, verbose_name='Komissiya stavkasi')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Komissiya miqdori (UZS)')),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Haydovchi daromadi (UZS)')),
                ('route_polyline', models.TextField(blank=True, null=True, verbose_name='Marshrut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='accounts.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Safar',
                'verbose_name_plural': 'Safarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField(verbose_name='Chiqish kengligi')),
                ('pickup_lng', models.FloatField(verbose_name='Chiqish uzunligi')),
                ('pickup_address', models.CharField(blank=True, max_length=255, verbose_name='Chiqish manzili')),
                ('drop_lat', models.FloatField(verbose_name='Tushish kengligi')),
                ('drop_lng', models.FloatField(verbose_name='Tushish uzunligi')),
                ('drop_address', models.CharField(blank=True, max_length=255, verbose_name='Tushish manzili')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxminiy narx (UZS)')),
                ('estimated_distance', models.FloatField(default=0, verbose_name='Taxminiy masofa (km)')),
                ('estimated_duration', models.IntegerField(default=0, verbose_name='Taxminiy vaqt (min)')),
                ('is_shared', models.BooleanField(default=True, verbose_name='Sherikli safar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('matched', 'Topildi'), ('accepted', 'Qabul qilindi'), ('cancelled', 'Bekor qilindi'), ('expired', "Muddati o'tdi"), ('completed', 'Yakunlandi')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='rides.ride', verbose_name='Safar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL, verbose_name="Yo'lovchi")),
            ],
            options={
                'verbose_name': "Safar so'rovi",
                'verbose_name_plural': "Safar so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Baho')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'unique_together': {('ride', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField(verbose_name='Chiqish kengligi')),
                ('pickup_lng', models.FloatField(verbose_name='Chiqish uzunligi')),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('drop_lat', models.FloatField(verbose_name='Tushish kengligi')),
                ('drop_lng', models.FloatField(verbose_name='Tushish uzunligi')),
                ('drop_address', models.CharField(blank=True, max_length=255)),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narx (UZS)')),
                ('pickup_order', models.IntegerField(default=1, verbose_name='Chiqish tartibi')),
                ('drop_order', models.IntegerField(default=1, verbose_name='Tushish tartibi')),
                ('picked_up', models.BooleanField(default=False, verbose_name='Olib ketildi')),
                ('dropped_off', models.BooleanField(default=False, verbose_name='Tushirildi')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_off_at', models.DateTimeField(blank=True, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='rides.ride', verbose_name='Safar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_participations', to=settings.AUTH_USER_MODEL, verbose_name="Yo'lovchi")),
                ('ride_request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_entry', to='rides.riderequest', verbose_name="So'rov")),
            ],
            options={
                'verbose_name': "Yo'lovchi",
                'verbose_name_plural': "Yo'lovchilar",
                'unique_together': {('ride', 'user')},
            },
        ),
    ]
