# Generated by Django 6.0.3 on 2026-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepassenger',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yetib kelgan vaqt'),
        ),
        migrations.AddField(
            model_name='ridepassenger',
            name='waiting_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kutish jarimasi (UZS)'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('searching', 'Qidirilmoqda'), ('driver_found', 'Haydovchi topildi'), ('on_the_way', "Yo'lda"), ('arrived', 'Yetib keldi'), ('started', 'Boshlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='searching', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('matched', 'Topildi'), ('accepted', 'Qabul qilindi'), ('arrived', 'Yetib keldi'), ('cancelled', 'Bekor qilindi'), ('expired', "Muddati o'tdi"), ('completed', 'Yakunlandi')], db_index=True, default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
