# Generated by Django 6.0.3 on 2026-04-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ridepassenger_arrived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Rejalashtirilgan'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Rejalashtirilgan'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejalashtirilgan vaqt'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='rides.ride')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referal bonus',
                'verbose_name_plural': 'Referal bonuslar',
            },
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(default=1)),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.riderequest')),
            ],
            options={
                'verbose_name': "Safar to'xtash joyi",
                'verbose_name_plural': "Safar to'xtash joylari",
                'ordering': ['order'],
            },
        ),
    ]
