# Generated by Django 6.0.3 on 2026-04-21 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_is_scheduled_riderequest_is_scheduled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralbonus',
            name='rides_completed',
            field=models.IntegerField(default=0, verbose_name='Bajarilgan safarlar'),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='rides_required',
            field=models.IntegerField(default=5, verbose_name='Kerakli safarlar soni'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tashqi buyurtma ID'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='external_provider',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tashqi xizmat (Yandex/Fasten/etc)'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='share_type',
            field=models.CharField(choices=[('solo', "Yolg'iz (Chegirmasiz)"), ('shared_1', '1 kishi bilan (20% chegirma)'), ('shared_2', '2 kishi bilan (30% chegirma)')], default='solo', max_length=10, verbose_name='Safar turi'),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonus miqdori'),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langan"),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilingan'),
        ),
        migrations.AlterField(
            model_name='referralbonus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilgan'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('matched', 'Topildi'), ('accepted', 'Qabul qilindi'), ('arrived', 'Yetib keldi'), ('cancelled', 'Bekor qilindi'), ('expired', "Muddati o'tdi"), ('completed', 'Yakunlandi'), ('external_pending', 'Tashqi buyurtma kutilmoqda')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
