# Generated by Django 6.0.3 on 2026-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='car_category',
            field=models.CharField(default='economy', max_length=20, verbose_name='Tanlangan avto sinfi'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='share_type',
            field=models.CharField(choices=[('solo', "Yolg'iz (Chegirmasiz)"), ('shared_1', '1 kishi bilan (20% chegirma)'), ('shared_2', '2 kishi bilan (30% chegirma)')], default='solo', max_length=20, verbose_name='Safar turi'),
        ),
    ]
