# Generated by Django 6.0.3 on 2026-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_riderequest_car_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='external_eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tashqi xizmat kelish vaqti'),
        ),
    ]
