# Generated by Django 6.0.3 on 2026-05-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_riderequest_external_eta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riderating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='riderating',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='riderating',
            unique_together={('ride', 'user', 'target_user')},
        ),
    ]
