# Generated by Django 6.0.3 on 2026-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_riderating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='use_bonus',
            field=models.BooleanField(default=False, verbose_name='Bonusdan foydalanish'),
        ),
    ]
