# Generated by Django 6.0.3 on 2026-05-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_riderequest_use_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='bonus_percent',
            field=models.IntegerField(default=100, verbose_name='Bonus foizi'),
        ),
    ]
