# Generated by Django 5.1.4 on 2026-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_riderequest_bonus_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hudud nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('lat_min', models.FloatField(verbose_name='Minimal kenglik (janub)')),
                ('lat_max', models.FloatField(verbose_name='Maksimal kenglik (shimol)')),
                ('lng_min', models.FloatField(verbose_name="Minimal uzunlik (g'arb)")),
                ('lng_max', models.FloatField(verbose_name='Maksimal uzunlik (sharq)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xizmat hududi',
                'verbose_name_plural': 'Xizmat hududlari',
            },
        ),
    ]
