# Generated by Django 5.1.4 on 2026-06-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_add_service_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('bonus', 'Bonus')], default='cash', max_length=10, verbose_name="To'lov usuli"),
        ),
    ]
